project_id = "fkpbdzluddeqsfvacozw"

[functions.transform-prompt]
verify_jwt = false

[functions.debug-console]
verify_jwt = true

[functions.generate-prompt-background]
verify_jwt = true

[functions.sync-to-loops]
verify_jwt = false