project_id = "fkpbdzluddeqsfvacozw"

[functions.execute-claude-code]
verify_jwt = true

[functions.validate-claude-token]
verify_jwt = false

[functions.transform-prompt]
verify_jwt = false

[functions.debug-console]
verify_jwt = true

[functions.generate-prompt-background]
verify_jwt = true

[functions.sync-to-loops]
verify_jwt = false

[functions.send-to-cursor]
verify_jwt = true

[functions.validate-github-token]
verify_jwt = true

[functions.validate-cursor-token]
verify_jwt = false

[functions.cursor-webhook]
verify_jwt = false

[functions.string-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true