-- Add generated prompt fields to prompts table
ALTER TABLE public.prompts 
ADD COLUMN generated_prompt TEXT NULL,
ADD COLUMN generated_at TIMESTAMP WITH TIME ZONE NULL;

-- Add comment for documentation
COMMENT ON COLUMN public.prompts.generated_prompt IS 'AI-generated version of the prompt for enhanced quality';
COMMENT ON COLUMN public.prompts.generated_at IS 'Timestamp when the prompt was generated by AI';