// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeStorage } from '@/lib/safeStorage';

const SUPABASE_URL = "https://fkpbdzluddeqsfvacozw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrcGJkemx1ZGRlcXNmdmFjb3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjYzOTYsImV4cCI6MjA3MjI0MjM5Nn0.-qO_uoXr6elt06BLqj6r5zmprCKHF043TdMZOeOWxxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});